name: Waka Readme

on:
  workflow_dispatch:
  push:
    branches:
      -main
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKA }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
